### ISSUE TITLE
Repo huidige leertaak

### ISSUE THREAD

**Issue by latoyaln** [reyrey-https/look-and-feel-corporate-identity#3]
Het is netjes als je in de Repo werkt van de huidige leertaak. Dat is nu '[look-and-feel-corporate-identity](https://github.com/reyrey-https/look-and-feel-corporate-identity)' je kan je code eventueel kopiëren hierheen en/of herschrijven.

Nu staat je code in the client website namelijk.

**Comment by reyrey-https** [comment]
Gefixt :)
